""" data file for The Count by Scott Adams """

from game_files.game_object import GameObject


VERBS = {
    "I": "INVENTORY",
    "N": "NORTH",
    "E": "EAST",
    "S": "SOUTH",
    "W": "WEST",
    "NOR": "NORTH",
    "EAS": "EAST",
    "SOU": "SOUTH",
    "WES": "WEST",
    "FLY": "FLY",
    "CLO": "CLOSE",
    "SHU": "SHUT",
    "OPE": "OPEN",
    "LIF": "LIFT",
    "RAI": "RAISE",
    "SLE": "SLEEP",
    "REA": "READ",
    "TO": "TO",
    "LOC": "LOCK",
    "UNL": "UNLOCK",
    "EXT": "EXTINGUISH",
    "LIG": "LIGHT",
    "BUR": "BURN",
    "IGN": "IGNORE",
    "JUM": "JUMP",
    "WAI": "WAIT",
    "EMP": "EMPTY",
    "SPI": "SPIN",
    "CUT": "CUT",
    "GO": "GO",
    "GET": "GET",
    "TAK": "TAKE",
    "LOO": "LOOK",
    "EXA": "EXAMINE",
    "USE": "USE",
    "PUT": "PUT",
    "DRO": "DROP",
    "TIE": "TIE",
    "UNT": "UNTIE",
    "BRE": "BREAK",
    "PUL": "PULL",
    "LOW": "LOWER",
    "CLI": "CLIMB",
    "EAT": "EAT",
    "DRI": "DRINK",
    "SMO": "SMOKE",
    "KIL": "KILL",
    "ATT": "ATTACK",
    "SAV": "SAVE",
    "LOA": "LOAD",
    "HEL": "HELP",
    "INV": "INVENTORY",
    "SCO": "SCORE",
    "RES": "RESTART",
    "DOW": "DOWN",
    "UP": "UP",
    "AUT": "AUTO",
    "ENT": "ENTER",
    "WIT": "WITH",
    "PIC": "PICK",
    "REM": "REMOVE",
    "CLE": "CLEAR",
    "WHE": "WHERE IS",
    "EVE": "EVENING",
    "MOV": "MOVES",
    "SIH": "SIHIR",
}

NOUNS = {
    "STA": "tent stake",
    "GAR": "dusty clove of garlic",
    "MAL": "rubber mallet",
    "MIR": "mirror",
    "WAT": "pocket watch",
    "TOR": "torch",
    "MAT": "sulfur matches",
    "FIL": "large tempered nail file",
    "PAC": "package",
    "CIG": "cigarette",
    "BOT": "bottle of Type V blood",
    "UP": "get up",
    "DUM": "dumbwaiter",
    "PIT": "pit of death",
    "SHE": "sheet", # sheet
    "RIN": "ring", # ring in the wall
    "POS": "postcard",
    "CLI": "paperclip",
    "NOT": "note",
    "VIA": "vial",
    "TAB": "tablets",
    "DOO": "door",
    "LOC": "lock",
    "OVE": "oven",
    "POR": "portrait of Dracula",
    "WIN": "window",
    "COF": "coffin",
    "BOL": "bolt",
    "DRA": "Dracula",
    "END": "end",
    "BED": "bed",
    "NOR": "North",
    "EAS": "Eath",
    "SOU": "South",
    "WES": "West",
    "ROO": "Room",
    "DOW": "Down",
    "VEN": "Vent",
    "PAS": "Passage",
    "SIG": "Sign",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "10",
}

GO = GameObject

# movable objects
OBJECT_DATA = [
    # key, name, location, plural,  movable
    ('SHE', 'sheet', 'bed', False, True),
    ('END', 'end of sheet', '', False, True),
    ('GAR', 'clove of garlic', 'pantry', False, True),
    ('MAT', 'matches', 'pantry', True, True),
    ('TOR', 'torch', '', False, True),
    ('PAC', 'pack of cigarettes', 'package', False, True),
    ('PKG', 'package', '', False, True),
    ('STA', 'tent stake', '', False, True),
    ('POS', 'postcard', 'courtyard', False, True),
    ('NOT', 'note', '', False, True),
    ('CLI', 'clip', '', False, True),
    ('VIA', 'vial', 'closet', False, True),
    ('TAB', 'tablets', 'closet', False, True),
    ('POR', "Dracula's portrait", "hanging", False, True),
    ('CIG', 'cigarette', '', False, True),
    ('FIL', 'broad file', 'oven', False, True),
    ('COF', "Coffin", "", False, False),
    ('MAL', 'Rubber mallet', 'workroom', False, True),
    ('DRA', 'Dracula', '', False, False),
    ('BOL', 'bolt', 'coffin', False, False),
]

delay: int | None = None
